# Generated by Django 5.2.6 on 2025-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='desc',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
