# Generated by Django 5.2.6 on 2025-10-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_boat_name_alter_amenity_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenites'},
        ),
    ]
