# Generated by Django 5.2.6 on 2025-10-22 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_boat_category'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='amenities',
            field=models.ManyToManyField(related_name='boats', to='boats.amenity'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL),
        ),
    ]
