# Generated by Django 5.2.6 on 2025-10-20 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boats', '0004_boat_category'),
        ('seaplatforms', '0002_seaplatform_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('boat', 'Boat'), ('seaplatform', 'Seaplatform')], max_length=15)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveIntegerField()),
                ('boat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boats.boat')),
                ('seaplatform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seaplatforms.seaplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
