# Generated by Django 5.2.6 on 2025-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
