# Generated by Django 5.2.6 on 2025-10-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boats', '0004_boat_category'),
        ('seaplatforms', '0002_seaplatform_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=140)),
                ('boat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.boat')),
                ('seaplatform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seaplatforms.seaplatform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('seaplatforms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seaplatforms.seaplatform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
