# Generated by Django 5.2.6 on 2025-10-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_boat_category'),
        ('reviews', '0001_initial'),
        ('seaplatforms', '0002_seaplatform_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.boat'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seaplatform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seaplatforms.seaplatform'),
        ),
    ]
