# Generated by Django 5.2.6 on 2025-10-22 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_alter_boat_amenities_alter_boat_category_and_more'),
        ('reviews', '0002_alter_review_boat_alter_review_seaplatform'),
        ('seaplatforms', '0003_alter_seaplatform_category_alter_seaplatform_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='boats.boat'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seaplatform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='seaplatforms.seaplatform'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
