# Generated by Django 5.2.6 on 2025-10-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('seaplatforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaplatform',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
