# Generated by Django 5.2.6 on 2025-10-22 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('seaplatforms', '0002_seaplatform_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaplatform',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seaplatforms', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='seaplatform',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaplatforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seaplatform',
            name='perks',
            field=models.ManyToManyField(related_name='seaplatforms', to='seaplatforms.perk'),
        ),
    ]
