# Generated by Django 5.2.6 on 2025-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaplatforms', '0003_alter_seaplatform_category_alter_seaplatform_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaplatform',
            name='people',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
